//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE kotus-sanalista SYSTEM &quot;kotus-sanalista.dtd&quot;&gt;
        ///&lt;!--
        ///Copyright (C) Kotimaisten kielten tutkimuskeskus 2006
        ///Kotimaisten kielten tutkimuskeskuksen nykysuomen sanalista, versio 1
        ///Julkaistu 15.12.2006
        ///
        ///Sanalista julkaistaan GNU LGPL -lisenssillä.
        ///Lisenssiteksti luettavissa osoitteessa http://www.gnu.org/licenses/lgpl.html
        ///--&gt;
        ///
        ///&lt;kotus-sanalista&gt;
        ///&lt;st&gt;&lt;s&gt;aakkonen&lt;/s&gt;&lt;t&gt;&lt;tn&gt;38&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosellinen&lt;/s&gt;&lt;t&gt;&lt;tn&gt;38&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosellisesti&lt;/s&gt;&lt;t&gt;&lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordlist {
            get {
                return ResourceManager.GetString("wordlist", resourceCulture);
            }
        }
    }
}
